version: '3.8'
services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=suse_db
      - OSS_ACCESS_KEY_ID=xxxxx
      - OSS_ACCESS_KEY_SECRET=xxxxx
      - OSS_ENDPOINT=https://oss-cn-shanghai.aliyuncs.com
      - OSS_BUCKET_NAME=for-kody-iso
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
  mysql:
    image: m.daocloud.io/docker.io/mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=suse_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data:
